# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your app into the container
COPY . /app/

# Expose port 5000 to allow communication with the outside world
EXPOSE 5000

# Define the command to run the Flask app
CMD ["python", "app.py"]
